version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    container_name: kanium-ss13-db
    labels:
      kompose.service.type: nodeport
    network_mode: 'host'
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=password123

 # ss13:
 #  image: 'kanium-ss13'
 #  container_name: kanium-ss13-server

volumes:
  mariadb_data:
    driver: local
